### PR TITLE
Add support for the options prop and autoplay

### PR DESCRIPTION
**Pull request by jan-be**
The readme says that you can put in an options prop, but you can't, so I added that functionality

Also I've added this repo's url to the package.json

### CODE REVIEW

**Comment by cliveportman** [comment]
Just seen this after marking it as an issue.

**Comment by PandaWhisperer** [comment]
Thanks for the bump @cliveportman. @JanBeckschewe, sorry I didn't respond earlier, haven't been using Svelte much recently. 

Code looks good, if it works I'll go ahead and merge it.

**Comment by cliveportman** [comment]
Thanks. Can you update on NPM?

**Comment by PandaWhisperer** [comment]
@cliveportman done.

**Pull request merged**
